=== AyserJamshidi/DarkBetrayal/gameserver/data/static_data/online_bonus/online_bonus.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="online_bonus_data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="bonus" type="Bonus" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Bonus">
		<xs:sequence>
			<xs:element name="reward_item" type="RewardItem" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="time_mins" type="xs:int"/>
		<xs:attribute name="reward_toll" type="xs:int"/>
		<xs:attribute name="reward_kinah" type="xs:int"/>
		<xs:attribute name="random" type="xs:boolean"/>
		<xs:attribute name="reset_time" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="RewardItem">
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="amount" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== AyserJamshidi/DarkBetrayal/gameserver/data/static_data/online_bonus/online_bonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<online_bonus_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="online_bonus.xsd">
    <!-- time_mins число кратное 5 -->
    <bonus time_mins="60" reward_toll="0" reward_kinah="0" random="true">
        <reward_item id="186000143" amount="3"/>
        <reward_item id="186000143" amount="5"/>
    </bonus>
	
	<bonus time_mins="120" reward_toll="0" reward_kinah="0" random="false">
        <reward_item id="186000051" amount="1"/>
    </bonus>
	
	<bonus time_mins="180" reward_toll="0" reward_kinah="0" random="true">
        <reward_item id="186000147" amount="1"/>
		<reward_item id="186000147" amount="2"/>
    </bonus>
	
	<bonus time_mins="240" reward_toll="1" reward_kinah="0" random="false" reset_time="true">
		<reward_item id="0" amount="0"/>
    </bonus>
    
</online_bonus_data>
